---
- name: Create the virtual machines
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        children:
          molecule:
            hosts: {}

  tasks:

    - name: Include tasks for platforms
      ansible.builtin.include_tasks:
        file: create-vm.yml
      loop: "{{ molecule_yml.platforms }}"

    - name: Fail if molecule group is missing
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: "molecule group was not found inside inventory groups: {{ groups }}"
      run_once: true

- name: Container post-create actions
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check os name
      ansible.builtin.command: cat /etc/redhat-release
      register: result
      changed_when: false

    - name: Display os name info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
...
