---
- name: Destroy molecule containers
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Include task list in play
      ansible.builtin.include_tasks:
        file: destroy-vm.yml
      loop: "{{ molecule_yml.platforms }}"

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        state: absent
