---
- name: Destroy a vm
  google.cloud.gcp_compute_instance:
    name: "{{ item.name }}"
    zone: "{{ item.zone }}"
    project: "{{ item.project }}"
    service_account_file: "{{ item.cred_file }}"
    auth_kind: "{{ item.cred_kind }}"
    state: absent

- name: Destroy an IP address for instance
  google.cloud.gcp_compute_address:
    name: "{{ item.name }}-ip"
    region: "{{ item.region }}"
    project: "{{ item.project }}"
    service_account_file: "{{ item.cred_file }}"
    auth_kind: "{{ item.cred_kind }}"
    state: absent
