---
- name: List all VMs
  community.libvirt.virt:
    command: list_vms
  register: all_vms

- name: Shutdown and remove existing machine
  when: item.name in all_vms.list_vms
  block:

    - name: Stop the VM
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: shutdown

    - name: Undefine the VM
      changed_when: false
      community.libvirt.virt:
        name: "{{ item.name }}"
        force: true
      ignore_errors: true

- name: Shutdown and remove existing machine
  become: true
  block:
    - name: Remove disk
      ansible.builtin.file:
        path: "{{ item.disk }}"
        state: absent
