---
platforms:
  - name: "${rocky8_name}"
    template: "${rocky8_image}"
    disk: "${pool}/${rocky8_name}-sda.qcow2"
    memory: "${memory}"
    machine: "${machine}"
    network: "${network}"

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
  inventory:
    links:
      group_vars: ../default/inventory/group_vars/
  env:
    ANSIBLE_ROLES_PATH: ../../../roles
...
